These are supported funding model platforms


patreon: https://www.patreon.com/c/JamesDSLiao
patreon: https://patreon.com/JamesDominicLiao_Nicoliao0918
buy_me_a_coffee: https://buymeacoffee.com/jamesliao02
ko-fi: https://ko-fi.com/jamesliao
paypal: https://paypal.me/liaoPH09
